In [68]:
import pandas as pd
import numpy as np
import ast

In [69]:
movies = pd.read_csv(r"/content/tmdb_5000_movies.csv")
credits = pd.read_csv(r"/content/tmdb_5000_credits.csv", engine='python')

In [70]:
movies = movies.merge(credits, on="title")

In [71]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [72]:
#movies.to_csv("tmdb_combined_raw.csv", index=False)


#print("Merged dataset saved successfully!")

In [73]:
#from google.colab import files

#files.download("tmdb_combined_raw.csv")

In [74]:
print(movies.shape)

(4809, 23)

In [75]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [76]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [77]:
movies.duplicated().sum()

np.int64(0)

In [78]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.809000e+03,4809.000000,4809.000000,4.809000e+03,4807.000000,4809.000000,4809.000000,4809.000000
mean,2.902780e+07,57120.571429,21.491664,8.227511e+07,106.882255,6.092514,690.331670,57120.571429
std,4.070473e+07,88653.369849,31.803366,1.628379e+08,22.602535,1.193989,1234.187111,88653.369849
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.800000e+05,9012.000000,4.667230,0.000000e+00,94.000000,5.600000,54.000000,9012.000000
50%,1.500000e+07,14624.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14624.000000
75%,4.000000e+07,58595.000000,28.350529,9.291317e+07,118.000000,6.800000,737.000000,58595.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [79]:
movies = movies[
[
'id',
'title',
'overview',
'tagline',
'genres',
'keywords',
'original_language',
'popularity',
'runtime',
'release_date',
'vote_average',
'cast',
'crew'
]
]

In [80]:
movies.dropna(subset=['tagline'], inplace=True)

In [81]:
movies.dropna(subset=['crew'], inplace=True)

In [82]:
movies.isnull().sum()

id                   0
title                0
overview             0
tagline              0
genres               0
keywords             0
original_language    0
popularity           0
runtime              0
release_date         0
vote_average         0
cast                 0
crew                 0
dtype: int64

In [83]:
def extract_names(text):
    names = []

    for item in ast.literal_eval(text):
        names.append(item['name'])

    return ", ".join(names)

movies['genres'] = movies['genres'].apply(extract_names)

In [84]:
movies.head()

,id,title,overview,tagline,genres,keywords,original_language,popularity,runtime,release_date,vote_average,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"Action, Adventure, Fantasy, Science Fiction","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,150.437577,162.0,2009-12-10,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","Adventure, Fantasy, Action","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,139.082615,169.0,2007-05-19,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"Action, Adventure, Crime","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,107.376788,148.0,2015-10-26,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"Action, Crime, Drama, Thriller","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,112.312950,165.0,2012-07-16,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","Action, Adventure, Science Fiction","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,43.926995,132.0,2012-03-07,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [85]:
movies['keywords'] = movies['keywords'].apply(extract_names)

In [86]:
def extract_cast(text):
    cast_names = []
    if not isinstance(text, str) or pd.isna(text) or not text.strip():
        return ""
    try:
        list_of_dicts = ast.literal_eval(text)
        for item in list_of_dicts[:3]:
            if isinstance(item, dict) and 'name' in item:
                cast_names.append(item['name'])
    except (ValueError, SyntaxError):
        return ""
    return ", ".join(cast_names)

# Ensure 'movies' DataFrame has the 'cast' column by re-merging and selecting if necessary
if 'cast' not in movies.columns:
    print("Warning: 'cast' column not found. Re-merging and re-selecting columns to reconstruct 'movies'.")
    # Re-merge `movies` and `credits`
    movies = movies.merge(credits, on="title")

    # Re-select necessary columns including 'cast'
    movies = movies[[
        'id',
        'title',
        'overview',
        'tagline',
        'genres',
        'keywords',
        'original_language',
        'popularity',
        'runtime',
        'release_date',
        'vote_average',
        'cast',
        'crew'
    ]]
    # Re-apply dropna operations that happened previously
    movies.dropna(subset=['tagline'], inplace=True)
    movies.dropna(subset=['crew'], inplace=True)

movies['cast'] = movies['cast'].apply(extract_cast)

In [87]:
movies.head()

,id,title,overview,tagline,genres,keywords,original_language,popularity,runtime,release_date,vote_average,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",en,150.437577,162.0,2009-12-10,7.2,"Sam Worthington, Zoe Saldana, Sigourney Weaver","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",en,139.082615,169.0,2007-05-19,6.9,"Johnny Depp, Orlando Bloom, Keira Knightley","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",en,107.376788,148.0,2015-10-26,6.3,"Daniel Craig, Christoph Waltz, Léa Seydoux","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",en,112.312950,165.0,2012-07-16,7.6,"Christian Bale, Michael Caine, Gary Oldman","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",en,43.926995,132.0,2012-03-07,6.1,"Taylor Kitsch, Lynn Collins, Samantha Morton","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [88]:
#movies.to_csv("tmdb_cleaned_step1.csv", index=False)

#print("Dataset saved successfully!")

In [89]:
#files.download("tmdb_cleaned_step1.csv")

In [90]:
def extract_crew(text):
    if not isinstance(text, str) or pd.isna(text) or not text.strip():
        return ""

    important_people = []

    try:
        crew_list = ast.literal_eval(text)

        for person in crew_list:
            if person.get("job") in ["Director", "Original Music Composer"]:
                important_people.append(person.get("name"))

        return ", ".join(important_people)

    except (ValueError, SyntaxError):
        return ""

movies["crew"] = movies["crew"].apply(extract_crew)

In [91]:
movies.head()

,id,title,overview,tagline,genres,keywords,original_language,popularity,runtime,release_date,vote_average,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",en,150.437577,162.0,2009-12-10,7.2,"Sam Worthington, Zoe Saldana, Sigourney Weaver","James Horner, James Cameron"
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",en,139.082615,169.0,2007-05-19,6.9,"Johnny Depp, Orlando Bloom, Keira Knightley","Gore Verbinski, Hans Zimmer"
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",en,107.376788,148.0,2015-10-26,6.3,"Daniel Craig, Christoph Waltz, Léa Seydoux","Thomas Newman, Sam Mendes"
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",en,112.312950,165.0,2012-07-16,7.6,"Christian Bale, Michael Caine, Gary Oldman","Hans Zimmer, Christopher Nolan"
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",en,43.926995,132.0,2012-03-07,6.1,"Taylor Kitsch, Lynn Collins, Samantha Morton",Andrew Stanton

In [92]:
#movies.to_csv("tmdb_cleaned_dataset.csv", index=False)
#files.download("tmdb_cleaned_dataset.csv")

In [95]:
movies['release_date'] = movies['release_date'].str[:4]

In [96]:
movies['release_date'] = movies['release_date'].str[:4].astype(int)

In [97]:
movies.head()

,id,title,overview,tagline,genres,keywords,original_language,popularity,runtime,release_date,vote_average,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",en,150.437577,162.0,2009,7.2,"Sam Worthington, Zoe Saldana, Sigourney Weaver","James Horner, James Cameron"
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",en,139.082615,169.0,2007,6.9,"Johnny Depp, Orlando Bloom, Keira Knightley","Gore Verbinski, Hans Zimmer"
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",en,107.376788,148.0,2015,6.3,"Daniel Craig, Christoph Waltz, Léa Seydoux","Thomas Newman, Sam Mendes"
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",en,112.312950,165.0,2012,7.6,"Christian Bale, Michael Caine, Gary Oldman","Hans Zimmer, Christopher Nolan"
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",en,43.926995,132.0,2012,6.1,"Taylor Kitsch, Lynn Collins, Samantha Morton",Andrew Stanton

In [98]:
movies["tags"] = (
    movies["genres"] + ". " +
    movies["keywords"] + ". " +
    movies["overview"] + ". " +
    movies["cast"] + ". " +
    movies["crew"]
)

In [99]:
movies.head()

,id,title,overview,tagline,genres,keywords,original_language,popularity,runtime,release_date,vote_average,cast,crew,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",en,150.437577,162.0,2009,7.2,"Sam Worthington, Zoe Saldana, Sigourney Weaver","James Horner, James Cameron","Action, Adventure, Fantasy, Science Fiction. c..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",en,139.082615,169.0,2007,6.9,"Johnny Depp, Orlando Bloom, Keira Knightley","Gore Verbinski, Hans Zimmer","Adventure, Fantasy, Action. ocean, drug abuse,..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",en,107.376788,148.0,2015,6.3,"Daniel Craig, Christoph Waltz, Léa Seydoux","Thomas Newman, Sam Mendes","Action, Adventure, Crime. spy, based on novel,..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",en,112.312950,165.0,2012,7.6,"Christian Bale, Michael Caine, Gary Oldman","Hans Zimmer, Christopher Nolan","Action, Crime, Drama, Thriller. dc comics, cri..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",en,43.926995,132.0,2012,6.1,"Taylor Kitsch, Lynn Collins, Samantha Morton",Andrew Stanton,"Action, Adventure, Science Fiction. based on n..."

In [101]:
movies.to_csv("tmdb_cleaned_dataset final.csv", index=False)
files.download("tmdb_cleaned_dataset final.csv")

In [104]:
movies.isnull().sum()

id                   0
title                0
overview             0
tagline              0
genres               0
keywords             0
original_language    0
popularity           0
runtime              0
release_date         0
vote_average         0
cast                 0
crew                 0
tags                 0
dtype: int64